version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: algotecture_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: algotecture
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: algotecture_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI

  redis:
    image: redis:7-alpine
    container_name: algotecture_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
      
  seq:
    image: datalust/seq:2024.3
    container_name: algotecture_seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=12345678
    volumes:
      - ./volumes/seq:/data
    ports:
      - "5101:80"    # UI
      - "5341:5341"  # ingestion endpoint for Serilog

volumes:
  pg_data:
  redis_data:
