name: Deploy Space Service

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag (default: latest)"
        required: false
        default: "latest"

jobs:
  deploy-space:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            set -e
            TAG="${{ github.event.inputs.tag || 'latest' }}"

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
                -u "${{ github.actor }}" --password-stdin

            cd /opt/algotecture

            export POSTGRES_CONNECTION="${{ secrets.POSTGRES_CONNECTION_SPACE }}"
            export SEQ_URL="${{ secrets.SEQ_URL }}"

            envsubst < ./config/space/appsettings.Template.json > ./generated/space/appsettings.json

            docker compose -f docker-compose.app.yml pull space
            docker compose -f docker-compose.app.yml up -d space

            docker image prune -f
